name: Fetch new content of tracked links and files

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'
  push:
    # trigger on updated linkbase
    branches:
      - main

jobs:
  fetch_new_content:
    name: Make files tree
    runs-on: ${{matrix.os}}
    continue-on-error: true
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: web
            os: macos-14

          - mode: web_res
            os: ubuntu-22.04

          - mode: web_tr
            os: ubuntu-22.04

          - mode: server
            os: ubuntu-22.04

          - mode: client
            os: macos-14

          - mode: mini_app
            os: ubuntu-22.04

    steps:

      - name: Clone.
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Python.
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies.
        run: |
          pip install -r requirements.txt

      - name: Generate files tree.
        env:
          OUTPUT_FOLDER: "data_ci/"
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          TELEGRAM_SESSION_TEST: ${{ secrets.TELEGRAM_SESSION_TEST }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          MODE: ${{ matrix.mode }}
        run: |
          git pull
          python make_files_tree.py
          rm -rf __pycache__

      - name: Prepare data.
        if: matrix.mode == 'web'
        run: |
          git checkout data
          git pull

          mv data/web_res data_ci/web_res
          mv data/web_tr data_ci/web_tr
          mv data/client data_ci/client
          mv data/server data_ci/server
          mv data/mini_app data_ci/mini_app

          rm -rf data
          mv data_ci data

      - name: Prepare data.
        if: matrix.mode == 'web_res'
        run: |
          git checkout data
          git pull

          mv data/web data_ci/web
          mv data/web_tr data_ci/web_tr
          mv data/client data_ci/client
          mv data/server data_ci/server
          mv data/mini_app data_ci/mini_app

          rm -rf data
          mv data_ci data

      - name: Prepare data.
        if: matrix.mode == 'web_tr'
        run: |
          git checkout data
          git pull

          mv data/web data_ci/web
          mv data/web_res data_ci/web_res
          mv data/server data_ci/server
          mv data/client data_ci/client
          mv data/mini_app data_ci/mini_app

          rm -rf data
          mv data_ci data

      - name: Prepare data.
        if: matrix.mode == 'server'
        run: |
          git checkout data
          git pull

          mv data/web data_ci/web
          mv data/web_res data_ci/web_res
          mv data/web_tr data_ci/web_tr
          mv data/client data_ci/client
          mv data/mini_app data_ci/mini_app

          rm -rf data
          mv data_ci data

      - name: Prepare data.
        if: matrix.mode == 'client'
        run: |
          git checkout data
          git pull

          mv data/web data_ci/web
          mv data/web_res data_ci/web_res
          mv data/web_tr data_ci/web_tr
          mv data/server data_ci/server
          mv data/mini_app data_ci/mini_app

          rm -rf data
          mv data_ci data

      - name: Prepare data.
        if: matrix.mode == 'mini_app'
        run: |
          git checkout data
          git pull

          mv data/web data_ci/web
          mv data/web_res data_ci/web_res
          mv data/web_tr data_ci/web_tr
          mv data/server data_ci/server
          mv data/client data_ci/client

          rm -rf data
          mv data_ci data

      - name: Commit and push changes.
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Update content of files"
          git push
